config:
  host: devx-helloworld-springboot-pk1ci
  namespace: devx-helloworld-springboot-pk1ci-service-dev
  image:
    name: uswest2fpmt.jfrog.io/devx-helloworld-springboot-pk1ci-docker-dev-local/devx-helloworld-springboot-pk1ci
    tag: v0.0.1
